services:
  postgres:
    image: postgres:latest
    container_name: pg-container
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: identitydb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-multiple-dbs.sql:/docker-entrypoint-initdb.d/init-dbs.sql

volumes:
  pgdata: