version: "3.8"

services:
    mysql:
        image: mysql:5.7
        container_name: mysql_container
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: mydatabase
            MYSQL_USER: myuser
            MYSQL_PASSWORD: mypassword
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_container
        restart: always
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: rootpassword
        ports:
            - "8081:80"
        depends_on:
            - mysql

volumes:
    mysql_data:
