# Stage 1: Build Go app cho Linux
FROM golang:1.20 AS builder

WORKDIR /app
COPY . .

# Khởi tạo module nếu chưa có
RUN go mod init go-docker-app || true
RUN go mod tidy

# Build binary cho Linux (Đảm bảo sử dụng GOOS=linux)
RUN GOOS=linux GOARCH=amd64 go build -o main .

# Stage 2: Run ứng dụng trong Alpine
FROM alpine:latest
RUN apk --no-cache add ca-certificates

WORKDIR /root/
COPY --from=builder /app/main .

EXPOSE 8080

CMD ["./main"]
