version: "3.8"

services:
    mysql:
        image: mysql:8.0
        container_name: mysql-container
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword # Mật khẩu cho user root (có thể đổi tuỳ ý)
            MYSQL_DATABASE: mydb # Tên database sẽ được tạo khi container khởi động
            MYSQL_USER: user # Tên user sẽ được tạo
            MYSQL_PASSWORD: password # Mật khẩu cho user
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql # Lưu trữ dữ liệu ra ngoài container

volumes:
    mysql-data:
